import { CVData } from '../model/cv';
import icCertificate from '../assets/images/IC-Certificate.pdf';

export const cvDataEn: CVData = {
  personalInfo: {
    name: 'Nguyen Hoai Thanh Ngoc',
    title: 'Front-end Developer',
    dateOfBirth: '23/05/1997',
    phone: '0363295271',
    email: 'mail@ngocnht.com',
    gender: 'Female',
  },
  education: {
    school: 'University of Information Technology - Vietnam National University Ho Chi Minh City',
    major: 'Computer Network and Communication',
    period: {
      start: 'Sept 2015',
      end: 'Jun 2020',
    },
    gpa: '7.8/10',
  },
  skills: [
    { name: 'JavaScript', category: 'language' },
    { name: 'TypeScript', category: 'language' },
    { name: 'CSS', category: 'language' },
    { name: 'HTML', category: 'language' },
    { name: 'ReactJS', category: 'framework' },
    { name: 'Bootstrap', category: 'library' },
    { name: 'Ant Design', category: 'library' },
    { name: 'Redux', category: 'library' },
  ],
  workExperience: [
    {
      company: 'GHN Express',
      position: 'Web Developer',
      period: {
        start: '6/2020',
        end: 'Now',
      },
      description: [
        'Developed and maintained multiple web applications using ReactJS and TypeScript, ensuring high code quality and performance.',
        'Collaborated with cross-functional teams including Product, Design, and Backend to deliver scalable front-end solutions.',
        'Mentored junior developers and onboarded new team members, improving team productivity and knowledge sharing.',
        'Architected and implemented reusable component libraries using Ant Design, reducing development time by 30%.',
        'Participated in technical discussions and contributed to architectural decisions for new projects.',
        'Optimized application performance through code splitting, lazy loading, and state management with Redux.',
      ],
      technologies: ['ReactJS', 'TypeScript', 'Redux', 'Ant Design', 'JavaScript'],
    },
    {
      company: 'Beesight Soft',
      position: 'Web Developer',
      period: {
        start: '6/2018',
        end: '2/2020',
      },
      description: [
        'Developed cross-platform mobile applications using PhoneGap and ReactJS for various client projects.',
        'Analyzed client requirements, evaluated project feasibility, and proposed technical solutions.',
        'Built responsive web applications with ReactJS, ensuring optimal user experience across devices.',
        'Collaborated with international clients to deliver high-quality software solutions.',
        'Gained experience in diverse project types including e-commerce, management systems, and training platforms.',
      ],
      technologies: ['ReactJS', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript'],
    },
  ],
  projects: [
    {
      name: 'Aligno — GHN Performance & OKR',
      role: 'Developer',
      period: {
        start: '05/2026',
        end: 'Now',
      },
      description: [
        'Shipped a greenfield back-office SPA for performance cycles, personal goals, and manager approvals on React 19 + Vite 5 + Ant Design 6 — modernizing how GHN runs OKR-style goal tracking with strict TypeScript and design tokens. | Giao SPA back-office mới cho chu kỳ đánh giá, mục tiêu cá nhân và phê duyệt quản lý trên React 19 + Vite 5 + Ant Design 6 — hiện đại hóa cách GHN vận hành mục tiêu kiểu OKR với TypeScript chặt và design token.',
        'Centralized all HTTP through a BFF axios wrapper plus TanStack Query 5 for caching, invalidation, and predictable loading/error UX across desktop and mobile shells. | Chuẩn hóa HTTP qua lớp axios BFF cùng TanStack Query 5 để cache, invalidate và trải nghiệm loading/ lỗi nhất quán trên layout desktop và mobile.',
        'Separated “components render, hooks think” per feature modules (Cycles, PersonalGoals, Dashboard) to keep UI thin and speed up onboarding for other engineers. | Tách “component chỉ render, hook xử lý logic” theo module (Cycles, PersonalGoals, Dashboard) để UI gọn và onboarding nhanh hơn cho team.',
        'Added Vitest + Testing Library coverage for critical flows and wired cookie-based SSO (`ghn_token`, `ghn_user_id`) with React Router 6 under basename `/aligno`. | Bổ sung Vitest + Testing Library cho luồng quan trọng và SSO cookie (`ghn_token`, `ghn_user_id`) với React Router 6 basename `/aligno`.',
      ],
      technologies: [
        'React 19',
        'TypeScript',
        'Vite 5',
        'Ant Design 6',
        'TanStack Query 5',
        'Zustand 5',
        'Axios (BFF)',
        'React Router 6',
        'Vitest',
        'SCSS',
      ],
      keywords: ['OKR', 'Performance Management', 'BFF', 'React Query', 'SSO', 'Design Tokens', 'Vitest'],
    },
    {
      name: 'Variable Pay & Benefits — Micro-frontend',
      role: 'Developer',
      period: {
        start: '06/2024',
        end: 'Now',
      },
      description: [
        'Own the `employee-benefit-web` micro-frontend packaged with Rspack + Module Federation, React 18.3, TailwindCSS, and pnpm so logistics compensation policies can ship independently from the legacy shell. | Phụ trách micro-frontend `employee-benefit-web` với Rspack + Module Federation, React 18.3, TailwindCSS và pnpm để chính sách lương thưởng logistics release độc lập khỏi shell cũ.',
        'Model complex driver pay, shipment incentives, and commission matrices with Formik + Zod adapters, guarded optimistic flows in TanStack Query 5, and resilient validation UX for finance reviewers. | Mô hình hóa lương tài xế, incentive vận đơn và ma trận hoa hồng bằng Formik + adapter Zod, optimistic flow có kiểm soát với TanStack Query 5 và UX validation rõ ràng cho tài chính.',
        'Automate exception queues, policy reruns, and rollback-friendly salary batches while pairing with Excel/XLSX tooling for bulk adjustments and audit-friendly exports. | Tự động hóa hàng ngoại lệ, rerun chính sách và batch lương an toàn rollback, kết hợp Excel/XLSX cho chỉnh sửa hàng loạt và export phục vụ kiểm soát.',
        'Invest in automated confidence via Jest component tests and Playwright CT hooks generated from the Rspack template, keeping regressions out of payroll-critical UI. | Đầu tư tự động hóa kiểm thử với Jest và Playwright CT theo template Rspack để giảm regression trên UI nhạy cảm lương.',
      ],
      technologies: [
        'React 18',
        'TypeScript',
        'Rspack',
        'Module Federation',
        'TanStack Query 5',
        'Formik',
        'Zod',
        'TailwindCSS',
        'pnpm',
        'Playwright',
        'Jest',
      ],
      keywords: [
        'Micro-frontend',
        'Logistics Compensation',
        'Policy Engine',
        'Variable Pay',
        'Quality Gates',
        'GHN',
      ],
    },
    {
      name: 'Payroll — Compensation Operations Suite',
      role: 'Developer',
      period: {
        start: '09/2022',
        end: 'Now',
      },
      description: [
        'Drive the payroll SPA (`homepage: hrm/payroll`) where Redux Saga orchestrates long-running payout jobs while TanStack Query 4 keeps payslip previews and bank-transfer batches synchronized for HRBP teams. | Chịu trách nhiệm SPA payroll (`homepage: hrm/payroll`) với Redux Saga điều phối job payout dài, TanStack Query 4 đồng bộ preview phiếu lương và batch chuyển khoản cho HRBP.',
        'Embed HyperFormula workbooks so commission analysts can tweak logic without redeploys, then surface results inside Ant Design tables virtualized for tens of thousands of rows. | Nhúng workbook HyperFormula để analyst chỉnh logic hoa hồng không cần redeploy, hiển thị trên bảng Ant Design được ảo hóa cho dataset lớn.',
        'Generate legally sensitive payslips via jsPDF + html2canvas pipelines, enrich narratives with Slate-based editors, and export accounting packages through ExcelJS + JSZip bundles. | Sinh phiếu lương nhạy cảm qua jsPDF + html2canvas, bổ sung mô tả bằng Slate, đóng gói báo cáo kế toán qua ExcelJS + JSZip.',
        'Instrument Recharts dashboards for accrual vs payout drift, debounced filters, and saga-backed retries when bank APIs throttle — giving finance a live control tower. | Xây dashboard Recharts theo dõi lệch accrual/payout, filter debounce và retry saga khi API ngân hàng throttle — control tower cho tài chính.',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Ant Design 4',
        'Redux',
        'Redux Saga',
        'TanStack Query 4',
        'HyperFormula',
        'Recharts',
        'Slate',
        'ExcelJS',
        'jsPDF',
      ],
      keywords: ['Payroll', 'Commission Engine', 'Payslip Automation', 'Bank Payout', 'Finance UX', 'GHN'],
    },
    {
      name: 'HRM Core — People Operations Backbone',
      role: 'Developer',
      period: {
        start: '04/2022',
        end: 'Now',
      },
      description: [
        'Evolve the `hrm/core` shell with feature toggles, route-level RBAC, and saga-isolated side effects so workforce policies can scale without entangling unrelated domains. | Phát triển shell `hrm/core` với feature toggle, RBAC theo route và side effect tách saga để mở rộng chính sách nhân sự không dính chéo domain.',
        'Deliver an interactive org chart (`react-organizational-chart`) with drag-and-drop moves, resize observers, and virtualized tables for enterprises exceeding 15k employees. | Bàn giao org chart tương tác (`react-organizational-chart`) kéo thả nhân sự, resize observer và bảng ảo cho doanh nghiệp >15k nhân viên.',
        'Digitize contract lifecycle, leave balances, and tax finalization with ExcelJS bulk import (50-row batches), diff-aware audit logs, and PDF tooling for e-contract evidence. | Số hóa vòng đời hợp đồng, số dư phép và quyết toán thuế với import ExcelJS theo batch 50 dòng, audit log diff-aware và PDF cho bằng chứng e-contract.',
        'Blend TanStack Query 4 optimistic updates with Cloudflare Turnstile-protected flows to keep sensitive HR actions both fast and guarded against abuse. | Kết hợp optimistic update TanStack Query 4 với luồng có Cloudflare Turnstile để thao tác HR nhạy cảm vừa nhanh vừa chống lạm dụng.',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Ant Design 4',
        'Redux',
        'Redux Saga',
        'TanStack Query 4',
        'react-organizational-chart',
        'ExcelJS',
        'jsPDF',
        'Turnstile',
      ],
      keywords: ['HRM', 'Org Chart', 'Contracts', 'Leave', 'RBAC', 'Audit Trail', 'GHN'],
    },
    {
      name: 'Candidate — Talent Acquisition Platform',
      role: 'Developer',
      period: {
        start: '04/2022',
        end: 'Now',
      },
      description: [
        'Maintain the `hrm/tuyendung` recruitment cockpit on React 16 + Ant Design 4 + Redux Saga, focusing on deterministic pipelines for high-volume hiring across GHN hubs. | Vận hành cockpit tuyển dụng `hrm/tuyendung` trên React 16 + Ant Design 4 + Redux Saga, tối ưu pipeline ổn định cho tuyển hàng loạt tại các hub GHN.',
        'Implement stage-based kanban, infinite scroll, and PubSub-driven notifications so recruiters collaborate without stale state when multiple editors touch one requisition. | Làm kanban theo stage, infinite scroll và thông báo PubSub để nhiều recruiter cùng thao tác một requisition không bị stale state.',
        'Instrument analytics for time-to-hire, funnel leakage, and interview load balancing using aggregated selectors + memoized charts to keep dashboards snappy on modest laptops. | Xây analytics time-to-hire, rò rỉ phễu và cân bằng lịch phỏng vấn bằng selector tổng hợp + chart memo hóa để dashboard mượt trên laptop phổ thông.',
        'Harden exports with `xlsx` / `xlsx-populate` templates so hiring managers can share sanitized candidate packets while preserving macro-enabled finance sheets where required. | Củng cố export `xlsx` / `xlsx-populate` để hiring manager chia sẻ gói ứng viên đã làm sạch, vẫn giữ sheet tài chính macro khi cần.',
      ],
      technologies: ['React', 'TypeScript', 'Ant Design 4', 'Redux', 'Redux Saga', 'React Window', 'XLSX'],
      keywords: ['ATS', 'Recruitment', 'High-volume Hiring', 'Analytics', 'Collaboration', 'GHN'],
    },
    {
      name: 'Cost — Procurement & Budget Control',
      role: 'Front-end Developer',
      period: {
        start: '01/2021',
        end: '03/2021',
      },
      description: [
        'Built the `qlns` procurement workspace on React 16 + React Bootstrap with Redux Saga routers that model multi-step approvals, conditional branches, and budget encumbrances synced to Oracle ERP REST endpoints with exponential backoff retries. | Xây workspace mua hàng `qlns` trên React 16 + React Bootstrap, Redux Saga mô hình hóa phê duyệt đa bước, nhánh có điều kiện và giữ ngân sách đồng bộ Oracle ERP REST với retry exponential backoff.',
        'Wove Firebase + Stream Chat into negotiation threads so buyers, finance, and vendors share evidence without leaving the approval timeline. | Tích hợp Firebase + Stream Chat vào luồng đàm phán để buyer, tài chính và NCC chia sẻ chứng từ ngay trên timeline phê duyệt.',
        'Delivered OCR-assisted invoice confirmation, duplicate detection in Excel ingestion, and immutable audit trails with compensating actions when buyers reversed a goods receipt. | Giao xác nhận hóa đơn hỗ trợ OCR, phát hiện trùng khi import Excel và audit trail bất biến kèm hành động bù khi hoàn hàng.',
      ],
      technologies: ['React', 'React Bootstrap', 'Redux', 'Redux Saga', 'Firebase', 'Stream Chat', 'Oracle REST', 'TypeScript'],
      keywords: ['Procurement', 'Budget', 'Oracle ERP', 'Realtime Chat', 'OCR', 'Compliance'],
    },
    {
      name: 'Eform — Dynamic Forms & Approvals',
      role: 'Front-end Developer',
      period: {
        start: '01/2021',
        end: '03/2021',
      },
      description: [
        'Authored a drag-and-drop form composer (`react-beautiful-dnd`) on Ant Design 4 with a schema-driven renderer covering conditional visibility, nested groups, and validator plugins shared across GHN back-offices. | Xây composer form kéo thả (`react-beautiful-dnd`) trên Ant Design 4 với renderer schema hỗ trợ hiển thị có điều kiện, nhóm lồng nhau và plugin validator dùng chung nhiều back-office GHN.',
        'Encoded parallel + serial approval graphs in Redux Saga, including delegation, SLA timers, and rollback-safe versioning whenever compliance teams tweaked templates. | Mã hóa đồ thị phê duyệt song song/tuần tự trong Redux Saga, gồm ủy quyền, SLA và versioning an toàn khi team compliance chỉnh template.',
        'Integrated TinyMCE-powered rich text blocks, PDF/Excel exports via `xlsx`, and optimistic autosave hooks so business users never lost long-running policy drafts. | Tích hợp khối rich text TinyMCE, export PDF/Excel qua `xlsx` và autosave optimistic để người dùng nghiệp vụ không mất bản nháp dài.',
      ],
      technologies: ['React', 'Ant Design 4', 'Redux', 'Redux Saga', 'react-beautiful-dnd', 'TinyMCE', 'TypeScript', 'XLSX'],
      keywords: ['Form Builder', 'Workflow', 'Compliance', 'Document Automation', 'GHN'],
    },
    {
      name: 'Fixle — Field Service Mobility',
      role: 'Developer',
      period: {
        start: '11/2018',
        end: '4/2019',
      },
      description: [
        'Delivered a PhoneGap-wrapped React experience with multi-role RBAC (master admin, provider, client) and offline-tolerant job boards for distributed technicians. | Giao trải nghiệm React bọc PhoneGap với RBAC đa vai và job board chịu offline cho kỹ thuật phân tán.',
        'Implemented GPS-aware dispatch, push notifications, and in-app messaging with lightweight dashboards for SLA-sensitive service markets. | Làm điều phối theo GPS, push notification và chat in-app cùng dashboard gọn cho thị trường dịch vụ nhạy SLA.',
        'Connected multiple payment gateways with Redux-audited transaction ledgers so finance could reconcile provider payouts nightly. | Kết nối nhiều cổng thanh toán với sổ giao dịch Redux để tài chính đối soát payout provider hàng đêm.',
      ],
      technologies: ['React', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript'],
      keywords: ['Field Service', 'Mobile', 'Payments', 'GPS Tracking'],
    },
    {
      name: 'Primary ITO — Offline-first Learning',
      role: 'Developer',
      period: {
        start: '3/2019',
        end: '12/2019',
      },
      description: [
        'Engineered an offline-first training companion with IndexedDB caches, background sync, and conflict resolution for learners in low-connectivity factories. | Thiết kế ứng dụng đào tạo offline-first với cache IndexedDB, đồng bộ nền và xử lý xung đột cho học viên nhà máy kết nối kém.',
        'Shipped jsPDF report packs with branded templates, milestone tracking widgets, and email hand-off flows for HR auditors. | Gói báo cáo jsPDF có template thương hiệu, widget milestone và luồng email cho HR kiểm toán.',
        'Wrapped Bootstrap forms with resilient validation so trainers could capture assessments even when airplanes mode interrupted mid-session. | Form Bootstrap có validation chắc để trainer thu thập đánh giá kể cả khi máy bay mode giữa phiên.',
      ],
      technologies: ['React', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript', 'IndexedDB', 'jsPDF'],
      keywords: ['LMS', 'Offline', 'PDF', 'Capability Tracking'],
    },
  ],
  certificates: [
    {
      name: 'Introduction to Cybersecurity',
      source: 'Cisco Network Academy',
      file: icCertificate,
    },
  ],
};

export const cvDataVn: CVData = {
  personalInfo: {
    name: 'Nguyễn Hoài Thanh Ngọc',
    title: 'Front-end Developer',
    dateOfBirth: '23/05/1997',
    phone: '0363295271',
    email: 'ngocnht.uit@gmail.com',
    gender: 'Nữ',
  },
  education: {
    school: 'Đại học Công nghệ Thông tin - Đại học Quốc gia Thành phố Hồ Chí Minh',
    major: 'Mạng máy tính và Truyền thông dữ liệu',
    period: {
      start: '09/2015',
      end: '06/2020',
    },
    gpa: '7.8/10',
  },
  skills: [
    { name: 'JavaScript', category: 'language' },
    { name: 'TypeScript', category: 'language' },
    { name: 'CSS', category: 'language' },
    { name: 'HTML', category: 'language' },
    { name: 'ReactJS', category: 'framework' },
    { name: 'Bootstrap', category: 'library' },
    { name: 'Ant Design', category: 'library' },
    { name: 'Redux', category: 'library' },
  ],
  workExperience: [
    {
      company: 'GHN Express',
      position: 'Web Developer',
      period: {
        start: '6/2020',
        end: 'Hiện tại',
      },
      description: [
        'Phát triển và bảo trì nhiều ứng dụng web sử dụng ReactJS và TypeScript, đảm bảo chất lượng code và hiệu suất cao.',
        'Hợp tác với các team đa chức năng bao gồm Product, Design và Backend để xây dựng các giải pháp front-end có khả năng mở rộng.',
        'Hướng dẫn các developer junior và onboard thành viên mới, cải thiện năng suất team và chia sẻ kiến thức.',
        'Thiết kế và xây dựng thư viện component tái sử dụng sử dụng Ant Design, giảm thời gian phát triển 30%.',
        'Tham gia thảo luận kỹ thuật và đóng góp vào các quyết định kiến trúc cho các dự án mới.',
        'Tối ưu hiệu suất ứng dụng thông qua code splitting, lazy loading và quản lý state với Redux.',
      ],
      technologies: ['ReactJS', 'TypeScript', 'Redux', 'Ant Design', 'JavaScript'],
    },
    {
      company: 'Beesight Soft',
      position: 'Web Developer',
      period: {
        start: '6/2018',
        end: '2/2020',
      },
      description: [
        'Phát triển ứng dụng mobile đa nền tảng sử dụng PhoneGap và ReactJS cho các dự án khách hàng đa dạng.',
        'Phân tích yêu cầu khách hàng, đánh giá tính khả thi dự án và đề xuất giải pháp kỹ thuật.',
        'Xây dựng ứng dụng web responsive với ReactJS, đảm bảo trải nghiệm người dùng tối ưu trên mọi thiết bị.',
        'Hợp tác với khách hàng quốc tế để cung cấp các giải pháp phần mềm chất lượng cao.',
        'Tích lũy kinh nghiệm với nhiều loại dự án bao gồm e-commerce, hệ thống quản lý và nền tảng đào tạo.',
      ],
      technologies: ['ReactJS', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript'],
    },
  ],
  projects: [
    {
      name: 'Aligno — Hiệu suất & OKR GHN',
      role: 'Developer',
      period: {
        start: '05/2026',
        end: 'Hiện tại',
      },
      description: [
        'Giao SPA back-office mới cho chu kỳ đánh giá, mục tiêu cá nhân và phê duyệt quản lý trên React 19 + Vite 5 + Ant Design 6 — hiện đại hóa cách GHN vận hành mục tiêu kiểu OKR với TypeScript chặt và design token. | Shipped a greenfield back-office SPA for performance cycles, personal goals, and manager approvals on React 19 + Vite 5 + Ant Design 6 — modernizing how GHN runs OKR-style goal tracking with strict TypeScript and design tokens.',
        'Chuẩn hóa HTTP qua lớp axios BFF cùng TanStack Query 5 để cache, invalidate và trải nghiệm loading/ lỗi nhất quán trên layout desktop và mobile. | Centralized all HTTP through a BFF axios wrapper plus TanStack Query 5 for caching, invalidation, and predictable loading/error UX across desktop and mobile shells.',
        'Tách “component chỉ render, hook xử lý logic” theo module (Cycles, PersonalGoals, Dashboard) để UI gọn và onboarding nhanh hơn cho team. | Separated “components render, hooks think” per feature modules (Cycles, PersonalGoals, Dashboard) to keep UI thin and speed up onboarding for other engineers.',
        'Bổ sung Vitest + Testing Library cho luồng quan trọng và SSO cookie (`ghn_token`, `ghn_user_id`) với React Router 6 basename `/aligno`. | Added Vitest + Testing Library coverage for critical flows and wired cookie-based SSO (`ghn_token`, `ghn_user_id`) with React Router 6 under basename `/aligno`.',
      ],
      technologies: [
        'React 19',
        'TypeScript',
        'Vite 5',
        'Ant Design 6',
        'TanStack Query 5',
        'Zustand 5',
        'Axios (BFF)',
        'React Router 6',
        'Vitest',
        'SCSS',
      ],
      keywords: ['OKR', 'Quản lý hiệu suất', 'BFF', 'React Query', 'SSO', 'Design token', 'Vitest'],
    },
    {
      name: 'Lương thưởng linh hoạt & phúc lợi — Micro-frontend',
      role: 'Developer',
      period: {
        start: '06/2024',
        end: 'Hiện tại',
      },
      description: [
        'Phụ trách micro-frontend `employee-benefit-web` với Rspack + Module Federation, React 18.3, TailwindCSS và pnpm để chính sách lương thưởng logistics release độc lập khỏi shell cũ. | Own the `employee-benefit-web` micro-frontend packaged with Rspack + Module Federation, React 18.3, TailwindCSS, and pnpm so logistics compensation policies can ship independently from the legacy shell.',
        'Mô hình hóa lương tài xế, incentive vận đơn và ma trận hoa hồng bằng Formik + adapter Zod, optimistic flow có kiểm soát với TanStack Query 5 và UX validation rõ ràng cho tài chính. | Model complex driver pay, shipment incentives, and commission matrices with Formik + Zod adapters, guarded optimistic flows in TanStack Query 5, and resilient validation UX for finance reviewers.',
        'Tự động hóa hàng ngoại lệ, rerun chính sách và batch lương an toàn rollback, kết hợp Excel/XLSX cho chỉnh sửa hàng loạt và export phục vụ kiểm soát. | Automate exception queues, policy reruns, and rollback-friendly salary batches while pairing with Excel/XLSX tooling for bulk adjustments and audit-friendly exports.',
        'Đầu tư tự động hóa kiểm thử với Jest và Playwright CT theo template Rspack để giảm regression trên UI nhạy cảm lương. | Invest in automated confidence via Jest component tests and Playwright CT hooks generated from the Rspack template, keeping regressions out of payroll-critical UI.',
      ],
      technologies: [
        'React 18',
        'TypeScript',
        'Rspack',
        'Module Federation',
        'TanStack Query 5',
        'Formik',
        'Zod',
        'TailwindCSS',
        'pnpm',
        'Playwright',
        'Jest',
      ],
      keywords: [
        'Micro-frontend',
        'Đãi ngộ logistics',
        'Engine chính sách',
        'Lương thưởng linh hoạt',
        'Quality gate',
        'GHN',
      ],
    },
    {
      name: 'Payroll — Bộ giải pháp vận hành lương',
      role: 'Developer',
      period: {
        start: '09/2022',
        end: 'Hiện tại',
      },
      description: [
        'Chịu trách nhiệm SPA payroll (`homepage: hrm/payroll`) với Redux Saga điều phối job payout dài, TanStack Query 4 đồng bộ preview phiếu lương và batch chuyển khoản cho HRBP. | Drive the payroll SPA (`homepage: hrm/payroll`) where Redux Saga orchestrates long-running payout jobs while TanStack Query 4 keeps payslip previews and bank-transfer batches synchronized for HRBP teams.',
        'Nhúng workbook HyperFormula để analyst chỉnh logic hoa hồng không cần redeploy, hiển thị trên bảng Ant Design được ảo hóa cho dataset lớn. | Embed HyperFormula workbooks so commission analysts can tweak logic without redeploys, then surface results inside Ant Design tables virtualized for tens of thousands of rows.',
        'Sinh phiếu lương nhạy cảm qua jsPDF + html2canvas, bổ sung mô tả bằng Slate, đóng gói báo cáo kế toán qua ExcelJS + JSZip. | Generate legally sensitive payslips via jsPDF + html2canvas pipelines, enrich narratives with Slate-based editors, and export accounting packages through ExcelJS + JSZip bundles.',
        'Xây dashboard Recharts theo dõi lệch accrual/payout, filter debounce và retry saga khi API ngân hàng throttle — control tower cho tài chính. | Instrument Recharts dashboards for accrual vs payout drift, debounced filters, and saga-backed retries when bank APIs throttle — giving finance a live control tower.',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Ant Design 4',
        'Redux',
        'Redux Saga',
        'TanStack Query 4',
        'HyperFormula',
        'Recharts',
        'Slate',
        'ExcelJS',
        'jsPDF',
      ],
      keywords: ['Payroll', 'Engine hoa hồng', 'Tự động phiếu lương', 'Chi trả ngân hàng', 'UX tài chính', 'GHN'],
    },
    {
      name: 'HRM Core — Nền tảng vận hành nhân sự',
      role: 'Developer',
      period: {
        start: '04/2022',
        end: 'Hiện tại',
      },
      description: [
        'Phát triển shell `hrm/core` với feature toggle, RBAC theo route và side effect tách saga để mở rộng chính sách nhân sự không dính chéo domain. | Evolve the `hrm/core` shell with feature toggles, route-level RBAC, and saga-isolated side effects so workforce policies can scale without entangling unrelated domains.',
        'Bàn giao org chart tương tác (`react-organizational-chart`) kéo thả nhân sự, resize observer và bảng ảo cho doanh nghiệp >15k nhân viên. | Deliver an interactive org chart (`react-organizational-chart`) with drag-and-drop moves, resize observers, and virtualized tables for enterprises exceeding 15k employees.',
        'Số hóa vòng đời hợp đồng, số dư phép và quyết toán thuế với import ExcelJS theo batch 50 dòng, audit log diff-aware và PDF cho bằng chứng e-contract. | Digitize contract lifecycle, leave balances, and tax finalization with ExcelJS bulk import (50-row batches), diff-aware audit logs, and PDF tooling for e-contract evidence.',
        'Kết hợp optimistic update TanStack Query 4 với luồng có Cloudflare Turnstile để thao tác HR nhạy cảm vừa nhanh vừa chống lạm dụng. | Blend TanStack Query 4 optimistic updates with Cloudflare Turnstile-protected flows to keep sensitive HR actions both fast and guarded against abuse.',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Ant Design 4',
        'Redux',
        'Redux Saga',
        'TanStack Query 4',
        'react-organizational-chart',
        'ExcelJS',
        'jsPDF',
        'Turnstile',
      ],
      keywords: ['HRM', 'Sơ đồ tổ chức', 'Hợp đồng', 'Nghỉ phép', 'RBAC', 'Audit log', 'GHN'],
    },
    {
      name: 'Candidate — Nền tảng tuyển dụng',
      role: 'Developer',
      period: {
        start: '04/2022',
        end: 'Hiện tại',
      },
      description: [
        'Vận hành cockpit tuyển dụng `hrm/tuyendung` trên React 16 + Ant Design 4 + Redux Saga, tối ưu pipeline ổn định cho tuyển hàng loạt tại các hub GHN. | Maintain the `hrm/tuyendung` recruitment cockpit on React 16 + Ant Design 4 + Redux Saga, focusing on deterministic pipelines for high-volume hiring across GHN hubs.',
        'Làm kanban theo stage, infinite scroll và thông báo PubSub để nhiều recruiter cùng thao tác một requisition không bị stale state. | Implement stage-based kanban, infinite scroll, and PubSub-driven notifications so recruiters collaborate without stale state when multiple editors touch one requisition.',
        'Xây analytics time-to-hire, rò rỉ phễu và cân bằng lịch phỏng vấn bằng selector tổng hợp + chart memo hóa để dashboard mượt trên laptop phổ thông. | Instrument analytics for time-to-hire, funnel leakage, and interview load balancing using aggregated selectors + memoized charts to keep dashboards snappy on modest laptops.',
        'Củng cố export `xlsx` / `xlsx-populate` để hiring manager chia sẻ gói ứng viên đã làm sạch, vẫn giữ sheet tài chính macro khi cần. | Harden exports with `xlsx` / `xlsx-populate` templates so hiring managers can share sanitized candidate packets while preserving macro-enabled finance sheets where required.',
      ],
      technologies: ['React', 'TypeScript', 'Ant Design 4', 'Redux', 'Redux Saga', 'React Window', 'XLSX'],
      keywords: ['ATS', 'Tuyển dụng', 'High-volume hiring', 'Phân tích', 'Cộng tác', 'GHN'],
    },
    {
      name: 'Cost — Mua sắm & kiểm soát ngân sách',
      role: 'Front-end Developer',
      period: {
        start: '01/2021',
        end: '03/2021',
      },
      description: [
        'Xây workspace mua hàng `qlns` trên React 16 + React Bootstrap, Redux Saga mô hình hóa phê duyệt đa bước, nhánh có điều kiện và giữ ngân sách đồng bộ Oracle ERP REST với retry exponential backoff. | Built the `qlns` procurement workspace on React 16 + React Bootstrap with Redux Saga routers that model multi-step approvals, conditional branches, and budget encumbrances synced to Oracle ERP REST endpoints with exponential backoff retries.',
        'Tích hợp Firebase + Stream Chat vào luồng đàm phán để buyer, tài chính và NCC chia sẻ chứng từ ngay trên timeline phê duyệt. | Wove Firebase + Stream Chat into negotiation threads so buyers, finance, and vendors share evidence without leaving the approval timeline.',
        'Giao xác nhận hóa đơn hỗ trợ OCR, phát hiện trùng khi import Excel và audit trail bất biến kèm hành động bù khi hoàn hàng. | Delivered OCR-assisted invoice confirmation, duplicate detection in Excel ingestion, and immutable audit trails with compensating actions when buyers reversed a goods receipt.',
      ],
      technologies: ['React', 'React Bootstrap', 'Redux', 'Redux Saga', 'Firebase', 'Stream Chat', 'Oracle REST', 'TypeScript'],
      keywords: ['Mua sắm', 'Ngân sách', 'Oracle ERP', 'Chat thời gian thực', 'OCR', 'Tuân thủ'],
    },
    {
      name: 'Eform — Form động & phê duyệt',
      role: 'Front-end Developer',
      period: {
        start: '01/2021',
        end: '03/2021',
      },
      description: [
        'Xây composer form kéo thả (`react-beautiful-dnd`) trên Ant Design 4 với renderer schema hỗ trợ hiển thị có điều kiện, nhóm lồng nhau và plugin validator dùng chung nhiều back-office GHN. | Authored a drag-and-drop form composer (`react-beautiful-dnd`) on Ant Design 4 with a schema-driven renderer covering conditional visibility, nested groups, and validator plugins shared across GHN back-offices.',
        'Mã hóa đồ thị phê duyệt song song/tuần tự trong Redux Saga, gồm ủy quyền, SLA và versioning an toàn khi team compliance chỉnh template. | Encoded parallel + serial approval graphs in Redux Saga, including delegation, SLA timers, and rollback-safe versioning whenever compliance teams tweaked templates.',
        'Tích hợp khối rich text TinyMCE, export PDF/Excel qua `xlsx` và autosave optimistic để người dùng nghiệp vụ không mất bản nháp dài. | Integrated TinyMCE-powered rich text blocks, PDF/Excel exports via `xlsx`, and optimistic autosave hooks so business users never lost long-running policy drafts.',
      ],
      technologies: ['React', 'Ant Design 4', 'Redux', 'Redux Saga', 'react-beautiful-dnd', 'TinyMCE', 'TypeScript', 'XLSX'],
      keywords: ['Form builder', 'Workflow', 'Tuân thủ', 'Tự động hóa tài liệu', 'GHN'],
    },
    {
      name: 'Fixle — Dịch vụ hiện trường',
      role: 'Developer',
      period: {
        start: '11/2018',
        end: '4/2019',
      },
      description: [
        'Giao trải nghiệm React bọc PhoneGap với RBAC đa vai và job board chịu offline cho kỹ thuật phân tán. | Delivered a PhoneGap-wrapped React experience with multi-role RBAC (master admin, provider, client) and offline-tolerant job boards for distributed technicians.',
        'Làm điều phối theo GPS, push notification và chat in-app cùng dashboard gọn cho thị trường dịch vụ nhạy SLA. | Implemented GPS-aware dispatch, push notifications, and in-app messaging with lightweight dashboards for SLA-sensitive service markets.',
        'Kết nối nhiều cổng thanh toán với sổ giao dịch Redux để tài chính đối soát payout provider hàng đêm. | Connected multiple payment gateways with Redux-audited transaction ledgers so finance could reconcile provider payouts nightly.',
      ],
      technologies: ['React', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript'],
      keywords: ['Field service', 'Mobile', 'Thanh toán', 'GPS'],
    },
    {
      name: 'Primary ITO — Đào tạo offline-first',
      role: 'Developer',
      period: {
        start: '3/2019',
        end: '12/2019',
      },
      description: [
        'Thiết kế ứng dụng đào tạo offline-first với cache IndexedDB, đồng bộ nền và xử lý xung đột cho học viên nhà máy kết nối kém. | Engineered an offline-first training companion with IndexedDB caches, background sync, and conflict resolution for learners in low-connectivity factories.',
        'Gói báo cáo jsPDF có template thương hiệu, widget milestone và luồng email cho HR kiểm toán. | Shipped jsPDF report packs with branded templates, milestone tracking widgets, and email hand-off flows for HR auditors.',
        'Form Bootstrap có validation chắc để trainer thu thập đánh giá kể cả khi máy bay mode giữa phiên. | Wrapped Bootstrap forms with resilient validation so trainers could capture assessments even when airplanes mode interrupted mid-session.',
      ],
      technologies: ['React', 'PhoneGap', 'Redux', 'Bootstrap', 'JavaScript', 'IndexedDB', 'jsPDF'],
      keywords: ['LMS', 'Offline', 'PDF', 'Theo dõi năng lực'],
    },
  ],
  certificates: [
    {
      name: 'Introduction to Cybersecurity',
      source: 'Cisco Network Academy',
      file: icCertificate,
    },
  ],
};
